eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: spring-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cusmer
    api-b:
      path: /api-b/**
      serviceId: service-feign
